FROM python:latest
ARG DEBIAN_FRONTEND=noninteractive
ENV PATH /usr/local/bin:$PATH
ENV LANG C.UTF-8
ENV TZ Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install -y python3 python3-pip libgl1-mesa-glx libglib2.0-0 tzdata
RUN pip install --upgrade pip
COPY ./requirements.txt /setup/requirements.txt
RUN pip install -r /setup/requirements.txt
# COPY ./app /app
WORKDIR /app